// User
export const CONNECT_APP_CALLBACK = 'CONNECT_APP_CALLBACK'
export const DELETE_USER_PHOTO = 'DELETE_USER_PHOTO'
export const DISCONNECT_APP = 'DISCONNECT_APP'
export const RECEIVE_CRAFT_ID_DATA = 'RECEIVE_CRAFT_ID_DATA'
export const SAVE_USER = 'SAVE_USER'
export const UPLOAD_USER_PHOTO = 'UPLOAD_USER_PHOTO'

// Licenses
export const CLAIM_CMS_LICENSE = 'CLAIM_CMS_LICENSE'
export const CLAIM_PLUGIN_LICENSE = 'CLAIM_PLUGIN_LICENSE'
export const GET_CMS_LICENSES = 'GET_CMS_LICENSES'
export const GET_PLUGIN_LICENSES = 'GET_PLUGIN_LICENSES'
export const RELEASE_CMS_LICENSE = 'RELEASE_CMS_LICENSE'
export const RELEASE_PLUGIN_LICENSE = 'RELEASE_PLUGIN_LICENSE'
export const SAVE_CMS_LICENSE = 'SAVE_CMS_LICENSE'
export const SAVE_LICENSE = 'SAVE_LICENSE'

// Plugins
export const SAVE_PLUGIN = 'SAVE_PLUGIN'
export const SUBMIT_PLUGIN = 'SUBMIT_PLUGIN'

// Cards
export const REMOVE_CARD = 'REMOVE_CARD'
export const SAVE_CARD = 'SAVE_CARD'

// Stripe
export const DISCONNECT_STRIPE_ACCOUNT = 'DISCONNECT_STRIPE_ACCOUNT'
export const RECEIVE_STRIPE_ACCOUNT = 'RECEIVE_STRIPE_ACCOUNT'
export const RECEIVE_STRIPE_CARD = 'RECEIVE_STRIPE_CARD'
export const RECEIVE_STRIPE_CUSTOMER = 'RECEIVE_STRIPE_CUSTOMER'
