#!/usr/bin/env php
<?php
/**
 * Craft console bootstrap file
 */

define('CRAFT_BASE_PATH', __DIR__);
define('CRAFT_VENDOR_PATH', CRAFT_BASE_PATH.'/vendor');

// Composer autoloader
require_once CRAFT_VENDOR_PATH.'/autoload.php';

// dotenv
if (file_exists(CRAFT_BASE_PATH.'/.env')) {
    $dotenv = new Dotenv\Dotenv(CRAFT_BASE_PATH);
    $dotenv->load();
}

if ($storagePath = getenv('CRAFT_STORAGE_PATH')) {
    define('CRAFT_STORAGE_PATH', $storagePath);
}

if ($keyPath = getenv('LICENSE_KEY_PATH')) {
    define('CRAFT_LICENSE_KEY_PATH', $keyPath);
}

define('CRAFT_ENVIRONMENT', getenv('CRAFT_ENV') ?: 'prod');

// Craft
$app = require CRAFT_VENDOR_PATH.'/craftcms/cms/bootstrap/console.php';
$exitCode = $app->run();
exit($exitCode);
